### ISSUE TITLE
npm run dev 页面无法打开

### ISSUE THREAD

**Issue by beileixinqing** [pspgbhu/react-isomorphic#3]
npm run dev  3000端口，显示无法访问此网站，没有任何报错。

**Comment by pspgbhu** [comment]
@beileixinqing  你把 package-lock.json 删除一下，再把 node_module 文件夹删除一下。然后用重新安装一下依赖。

**Comment by pspgbhu** [comment]
@beileixinqing  是之前 lock 的依赖包有问题导致的

**Comment by beileixinqing** [comment]
> @beileixinqing 是之前 lock 的依赖包有问题导致的

删掉 package-lock.json ,也重新安装了npm包，依然打不开

**Comment by pspgbhu** [comment]
有相关错误提示的截图吗 @beileixinqing

**Comment by beileixinqing** [comment]
![image](https://user-images.githubusercontent.com/22930400/50880584-e0d05b80-1419-11e9-90de-70a14e11ffba.png)

**Comment by beileixinqing** [comment]
![image](https://user-images.githubusercontent.com/22930400/50880607-f2196800-1419-11e9-8d05-8ef9b83f1b03.png)

**Comment by pspgbhu** [comment]
http://127.0.0.1:3000
