### ISSUE TITLE
请问图片要在放置在哪一个档案夹内

### ISSUE THREAD

**Issue by ErnieHan** [pspgbhu/react-isomorphic#4]
![0](https://user-images.githubusercontent.com/42028425/54901093-6ab79d00-4f10-11e9-951d-789bb714946a.PNG)
![02](https://user-images.githubusercontent.com/42028425/54901103-71deab00-4f10-11e9-91f9-03cb1e47d87f.PNG)

目前把图片放置在这里 不过无法正确显示图片
请问要在放置在哪一个档案夹内 谢谢!

**Comment by pspgbhu** [comment]
@ErnieHan  server/public/ 文件夹是一个挂载在根路径上的静态资源目录，你可以把图片放在这个目录下。
比如 `server/public/assets/01.jpg`，你就可以通过路径 /assets/01.jpg 访问

**Comment by ErnieHan** [comment]
@pspgbhu 显示成功了! 谢谢
